### PR TITLE
Backport 3.8

### PR DESCRIPTION
**Pull request by zhfeng**

### CODE REVIEW

**Comment by JiriOndrusek** [comment]
@ppalaga is it OK to merge this backport PR and cut the release of 3.8.4?

**Comment by ppalaga** [comment]
I'll try to review/merge later today.

**Comment by ppalaga** [comment]
Could you please add https://github.com/quarkiverse/quarkus-cxf/commit/d9a77705cf929398e050e1c4a975af9e035e536f at the very beginning and https://github.com/quarkiverse/quarkus-cxf/commit/3289a7720d188ba10ddcc454c068c2044c4135e2 at the very end? I tend to keep all release announcements in all branches.

**Comment by zhfeng** [comment]
Thanks @ppalaga - I add these two commits.

**Review by JiriOndrusek — APPROVED** [review]

**Pull request merged**
