### PR TITLE
Trigger release 1.5.0.CR1

### PR DESCRIPTION
**Pull request by ppalaga**
Attempt no. 2.

### CODE REVIEW

**Comment by ppalaga** [comment]
This worked 🎉

1.5.0.CR1 is available on Central: https://repo1.maven.org/maven2/io/quarkiverse/cxf/quarkus-cxf/1.5.0.CR1/

@famod @shumonsharif any feedback about this release would be welcome

**Comment by famod** [comment]
@ppalaga I gave it a quick try in my current project (client only) and it's looking good so far. Great job!

**Comment by shumonsharif** [comment]
@ppalaga Nice work, and great job indeed!  

My only minor suggestion is that the docs will need some updates, especially with regard to the introduction of the BOMs, though that doesn't necessarily need to coincide with the release.

**Comment by ppalaga** [comment]
> the docs will need some updates, especially with regard to the recent introduction of the BOMs, though that doesn't necessarily need to coincide with the release.

Good idea. I filled https://github.com/quarkiverse/quarkus-cxf/issues/512 so that we do not forget.

**Pull request merged**
