### PR TITLE
Uberjar

### LINKED ISSUE #194: Packaged application gives error message: Could not resolve a binding for http://schemas.xmlsoap.org/wsdl/soap/
When using the application with dev mode ( without packaging ) everything works perfectly. But after we package it as an uber-jar it gives the following error:
````
Could not resolve a binding for http://schemas.xmlsoap.org/wsdl/soap/
````

We are using quarkus-cxf version 0.5 and quarkus version 1.11.3.Final.

If you need more information, please let me know.

### PR DESCRIPTION
**Pull request by dufoli**
fix #194

### CODE REVIEW

**Comment by shumonsharif** [comment]
@dufoli What do you think of something like this?  Still a lot of code, but possibly slightly cleaner ... 

```java
    public static void main(String... args) throws IOException, XPathExpressionException, ParserConfigurationException, SAXException, TransformerException {
        XPath xpath = XPathFactory.newInstance().newXPath();
        DocumentBuilder builder = DocumentBuilderFactory.newInstance().newDocumentBuilder();

        ClassLoader loader = Thread.currentThread().getContextClassLoader();
        Enumeration<URL> urls = loader.getResources("META-INF/wsdl.plugin.xml");

        // Create output / merged document
        Document mergedXmlDocument = builder.newDocument();
        Element root = mergedXmlDocument.createElement("properties");
        mergedXmlDocument.appendChild(root);
        for (URL url : Collections.list(urls)) {
            BufferedReader reader = new BufferedReader(new InputStreamReader(url.openStream()));
            String content = reader.lines().collect(Collectors.joining(System.lineSeparator()));
            Document dDoc = builder.parse(new InputSource(new StringReader(content)));
            NodeList nodeList = (NodeList) xpath.compile("//entry").evaluate(dDoc, XPathConstants.NODESET);
            for (int i = 0; i < nodeList.getLength(); i++) {
                Node node = nodeList.item(i);
                Node copyNode = mergedXmlDocument.importNode(node, true);
                root.appendChild(copyNode);
            }
        }

        ByteArrayOutputStream os = new ByteArrayOutputStream();
        Transformer transformer = TransformerFactory.newInstance().newTransformer();
        transformer.setOutputProperty(OutputKeys.INDENT, "yes");
        transformer.transform(new DOMSource(mergedXmlDocument),
                new StreamResult(new OutputStreamWriter(os, "UTF-8")));

        System.out.println("MERGED CONTENTS BELOW");
        System.out.println(os.toString());
    }
```

**Comment by dufoli** [comment]
@shumonsharif yes it is better but we have to handle issue like empty file, broken xml, missing node and so on...

**Comment by shumonsharif** [comment]
Yes agreed @dufoli ... it was just a quick and dirty representation of what the merge / combine code could potentially look like, not the actual solution ... and it's really not that much different from what you already have in your branch in terms of how clean it looks (both codes make me a little queasy)!!! ... so if you wish, please feel free to integrate, or let me know if you're ok with commit to the uber branch and I can do it.

**Comment by dufoli** [comment]
I have add your code and indeed all exception seems to do the trick.
Just have to test it now ;-)

**Comment by dufoli** [comment]
@shumonsharif LGTM and wait next quarkus release for it ?

**Comment by shumonsharif** [comment]
@dufoli I think 1.13.5.Final is scheduled for a few days from now, it has the fix; so this is good.

**Comment by dufoli** [comment]
@shumonsharif  when 1.13.5.Final is released I take it and release 0.7

**Comment by marcelbraghini** [comment]
> @shumonsharif when 1.13.5.Final is released I take it and release 0.7

hello, can you tell me when it comes out and what will be the version of quarkus-cxf for this case?

**Pull request merged**
