### PR TITLE
WS-Security native mode support

### PR DESCRIPTION
**Pull request by shumonsharif**
This should address #354 ; docs have been updated to provide additional details regarding WS-Security native mode support.

@famod Would you kindly review when you have some time?  Thanks in advance!

### CODE REVIEW

**Comment by shumonsharif** [comment]
BTW @famod I couldn't find a good way to deal with the `--allow-incomplete-classpath` flag for two optional transitive dependencies that were missing from the classpath during the native build:

- `org.jvnet.mimepull:mimepull`
- `org.apache.cxf:cxf-rt-ws-mex`

I tried the [NativeImageAllowIncompleteClasspathBuildItem](https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/NativeImageAllowIncompleteClasspathBuildItem.java), but it not only printed a stark warning, it also did not seem like a good option anyway.

I also couldn't find any properties (Maven or Quarkus) that would force the inclusion of optional dependencies - in the end, I just updated the docs to say that one would need to include the two optional dependencies in their WS-Security project for the native build to work.

**Comment by famod** [comment]
Just saw this. I'll try to have a look later this week.

**Comment by shumonsharif** [comment]
A few notes:

- I was trying to avoid introducing a dependency on `cxf-rt-ws-security` for the extension.
- I had strongly considered splitting up the codebase to introduce sub-modules for [each of the `cxf-rt-ws-*`](https://github.com/apache/cxf/tree/master/rt/ws) dependencies.  While it would simplify and result in significantly cleaner code, it'll be a major refactoring and involved effort.  I feel it is the better approach, and will keep looking into it, though my bandwidth is limited.
- There is some odd behavior with the GraalvM native image and locales that I could not quite get to the bottom of (I'd need to debug the native image), which resulted in the introduction of this [somewhat odd method](https://github.com/quarkiverse/quarkus-cxf/pull/364/files#diff-6d93c9f954f11ebbae9fbae363f3d64e4862b54dc79f44df3ffd257574e7b3a5R276).  Basically, the properties defined in wss4j_errors.properties were not available as a resource bundle (tried numerous approaches to address the issue); in the end I merged the properties into a bundle that is.

**Comment by shumonsharif** [comment]
@famod I'm thinking of merging this in for now; let me know in case in case I should hold off, or you can always do a retroactive review once you have some time - and will make any corrections at that point in time.

**Pull request merged**
