### PR TITLE
Dependabot: ignore jakarta.xml.ws-api >= 3.0.0

### PR DESCRIPTION
**Pull request by famod**
Should prevent PRs like #200

### CODE REVIEW

**Comment by shumonsharif** [comment]
@famod @dufoli I think our jakarta.xml.ws-api dependency version should depend on what the CXF libraries depend on.  I'm not sure if CXF plans to update to anything >= 3.0.0 but in case that happens in the future, won't this PR impact us at that point?

**Comment by shumonsharif** [comment]
Gotcha, makes sense @famod.  In a way, it is indeed better that this dependency is not managed by dependabot as it can possibly lead to incongruent versions.  We'll just need to keep it in mind when we update CXF.  Including this link here for reference:  https://cxf.apache.org/docs/migration-guides.html

**Comment by famod** [comment]
I actually went for `>= 0` in a Maven extension I'm maintaining: https://github.com/gitflow-incremental-builder/gitflow-incremental-builder/blob/master/.github/dependabot.yml
It just doesn't make sense to let the bot (try to) bump everything.

**Comment by shumonsharif** [comment]
Yes, I would suggest we do the same here as well.  @dufoli wdyt?

**Pull request merged**
