### PR TITLE
Docsoap

### LINKED ISSUE #205: SOAP 1.2?
I stumbled upon this:
https://github.com/quarkiverse/quarkus-cxf/blob/9569c3cc504a2dec9e56ca412cd300ea68334d00/deployment/src/main/java/io/quarkiverse/cxf/deployment/QuarkusCxfProcessor.java#L209-L210

Does that mean that currently only SOAP 1.1 clients are supported?

### LINKED ISSUE #274: document HTTPConduitConfigurer trick
idea is to explain how HTTPConduitConfigurer can help to configure authentication...

example:
```
void onStart(@Observes StartupEvent ev) {
     
     HTTPConduitConfigurer httpConduitConfigurer = new HTTPConduitConfigurer() {
         public void configure(String name, String address, HTTPConduit c) {
             AsyncHTTPConduit conduit = (AsyncHTTPConduit)c;
             DefaultHttpAsyncClient defaultHttpAsyncClient;
             defaultHttpAsyncClient = conduit.getHttpAsyncClient();
             defaultHttpAsyncClient.getCredentialsProvider().setCredentials( AuthScope.ANY,
              new NTCredentials( USER,PWD, "", DOM ) );
             conduit.getClient().setAllowChunking( false );
             conduit.getClient().setAutoRedirect( true );
         }
     };

     final Bus bus = BusFactory.getThreadDefaultBus();
     bus.setExtension(httpConduitConfigurer, HTTPConduitConfigurer.class);
 }
```

### PR DESCRIPTION
**Pull request by dufoli**
fix #274 
fix #205

### CODE REVIEW

**Comment by dufoli** [comment]
@shumonsharif  @famod  if you want, you can review new doc and cleanup of unused config (switch from endpoint to client config)

**Comment by famod** [comment]
@dufoli so username and password basic auth was just "prepared" by providing config items but it wasn't really implemented at all?

**Comment by shumonsharif** [comment]
@dufoli I will take a look at this shortly - there are numerous ways to leverage the HttpConduit, it may be worth mentioning the variety of things you can do with it.

@famod Is this PR the one you are referring to?  Basic auth looked like it was implemented.
https://github.com/quarkiverse/quarkus-cxf/pull/48/files#diff-8da8add3462dee7543a9c82500ab6d8207d557648d343645982a249b48133fd4R43

**Comment by dufoli** [comment]
@famod it was for client only

**Pull request merged**
