### PR TITLE
Fix docs build

### PR DESCRIPTION
**Pull request by gastaldi**
This fixes the releasing issue

### CODE REVIEW

**Comment by gastaldi** [comment]
FYI, I just changed the pom.xml, the other files were included when `mvn clean package` was executed

**Comment by gastaldi** [comment]
You mean in the `templates` dir? They are used to generate these files

**Comment by famod** [comment]
No, I mean:
- https://github.com/quarkiverse/quarkus-cxf/blob/main/docs/modules/ROOT/pages/attributes.adoc
- https://github.com/quarkiverse/quarkus-cxf/blob/main/docs/modules/ROOT/pages/quarkus-cxf.adoc

**Comment by gastaldi** [comment]
Ah these can be safely deleted, I'll update the PR

**Review by famod — APPROVED** [review]
LGTM (I think)

**Comment by famod** [comment]
@gastaldi might have found something else to clean up: https://github.com/quarkiverse/quarkus-cxf/blob/main/.github/workflows/release.yml#L50-L53

**Pull request merged**
