### PR TITLE
Adds tips-and-ticks documentation page

### PR DESCRIPTION
**Pull request by aruffie**
One idea for documentation updating, what do you think about it ?

### CODE REVIEW

**Comment by shumonsharif** [comment]
I like the tips and tricks page, great idea @aruffie !!  BTW, I see some grammatical and spelling mistakes, do you mind if I go ahead and correct them?

**Comment by aruffie** [comment]
> I like the tips and tricks page, great idea @aruffie !! BTW, I see some grammatical and spelling mistakes, do you mind if I go ahead and correct them?

Of course, do whatever you want :-) Even if I am careful, since I do not live in an anglophone country, it is difficult to be really strong in English.

I hope quickly help you for tickets which will be need to fix in the future :-)

**Comment by shumonsharif** [comment]
Thanks @aruffie ... I am tied up most of this week; I will work on it this weekend.

BTW, @dufoli and @aruffie ... je comprends un peu le français (thanks to high school french classes, though it was a very long time ago)!!

**Comment by aruffie** [comment]
@shumonsharif 
> Thanks @aruffie ... I am tied up most of this week; I will work on it this weekend.
> 
> BTW, @dufoli and @aruffie ... je comprends un peu le français (thanks to high school french classes, though it was a very long time ago)!!

Nice song ! If you need to increase your's french skill, web can talk together in french on zulipchat 😊

**Pull request merged**
