### PR TITLE
Add PARAMETER target to CXFClient

### LINKED ISSUE #242: constructor injection not possible with CXFClient
Thanks for adding `io.quarkiverse.cxf.annotation.CXFClient`!

Too bad it lacks the `PARAMETER`-Target to be used in constructor injection:
```
@ApplicationScoped
class MyService {
    private final SomeBean someBean;
    private final TheCxfApi apiClient;

    public MyService(SomeBean someBean, @CXFClient("name_in_config") TheCxfApi apiClient) {
        this.someBean = someBean;
        this.apiClient = apiClient;
    }
}
```

Please enable usage for parameters, otherwise constructor injection is simply not possible.

### PR DESCRIPTION
**Pull request by famod**
Fixes #242

### CODE REVIEW

**Comment by gastaldi** [comment]
@all-contributors add @famod for code and maintenance

**Comment by dufoli** [comment]
@shumonsharif readme.adoc replace readme.md but it fail because all contributors request it.
Why do you switch to adoc? I do not remember ;-)

**Comment by shumonsharif** [comment]
@dufoli @gastaldi we switched to adoc because we were originally trying to include sections from the antora docs inside the README, so we could only maintain in one place.  That ended up not working too well.  I think we can switch back to README.md, I will fix that today.

**Comment by shumonsharif** [comment]
@all-contributors add @famod for code and maintenance

**Pull request merged**
