### PR TITLE
Large responses written slowly due to allocating too small buffers

### LINKED ISSUE #1066: Large responses written slowly due to allocating too small buffers
I have found evidence of slow performance of Quarkus CXF extension.
In a nutshell, a single invocation of a SOAP endpoint takes about 10 seconds to return a response. The performance further degrades when concurrent calls are made.

From my initial analysis, I can see that the main Thread that replies to your request interacts with Saxon parsing library for most of the time, until the stream of data is returned to the customer:
```
"vert.x-worker-thread-0" #114 prio=5 os_prio=0 cpu=8272.53ms elapsed=222.58s tid=0x00007f438c0daa70 nid=0x2d1a runnable  [0x00007f44fb2fa000]
   java.lang.Thread.State: RUNNABLE
at com.sun.org.apache.xerces.internal.dom.ParentNode.nodeListItem(java.xml@17.0.2/ParentNode.java:766)
at com.sun.org.apache.xerces.internal.dom.ParentNode.item(java.xml@17.0.2/ParentNode.java:797)
at net.sf.saxon.dom.DOMNodeWrapper$ChildEnumeration.skipFollowingTextNodes(DOMNodeWrapper.java:1122)
at net.sf.saxon.dom.DOMNodeWrapper$ChildEnumeration.next(DOMNodeWrapper.java:1159)
- locked <0x000000045182aaa8> (a com.sun.org.apache.xerces.internal.dom.DeferredDocumentImpl)
at net.sf.saxon.tree.util.Navigator$EmptyTextFilter.next(Navigator.java:1292)
at net.sf.saxon.tree.util.Navigator$EmptyTextFilter.next(Navigator.java:1274)
at net.sf.saxon.tree.iter.LookaheadIteratorImpl.next(LookaheadIteratorImpl.java:53)
at net.sf.saxon.tree.jiter.WrappingJavaIterator.next(WrappingJavaIterator.java:48)
at net.sf.saxon.tree.jiter.WrappingJavaIterator.next(WrappingJavaIterator.java:24)
at net.sf.saxon.tree.util.Navigator.copy(Navigator.java:695)
. . . .
"vert.x-worker-thread-0" #114 prio=5 os_prio=0 cpu=15308.80ms elapsed=230.93s tid=0x00007f438c0daa70 nid=0x2d1a runnable  [0x00007f44fb2fc000]
   java.lang.Thread.State: RUNNABLE
at com.sun.org.apache.xerces.internal.dom.ParentNode.internalInsertBefore(java.xml@17.0.2/ParentNode.java:371)
at com.sun.org.apache.xerces.internal.dom.ParentNode.insertBefore(java.xml@17.0.2/ParentNode.java:286)
at com.sun.org.apache.xerces.internal.dom.NodeImpl.appendChild(java.xml@17.0.2/NodeImpl.java:230)
at org.apache.cxf.staxutils.W3CDOMStreamWriter.writeCharacters(W3CDOMStreamWriter.java:311)
at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:759)
at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:707)
at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:633)
at org.apache.cxf.databinding.source.XMLStreamDataWriter.write(XMLStreamDataWriter.java:127)
at org.apache.cxf.databinding.source.XMLStreamDataWriter.write(XMLStreamDataWriter.java:68)
at org.apache.cxf.databinding.source.XMLStreamDataWriter.write(XMLStreamDataWriter.java:56)

```
I'm attaching a reproducer for the endpoint available at: http://localhost:8080/foo/ReferenceData?wsdl
Here is a sample SOAP request you can use for a test:

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ref="http://fuse.ml.cbs.alpha.gr/ReferenceData/">
   <soapenv:Header/>
   <soapenv:Body>
<ref:getListReferenceDataItem xmlns:ref="http://fuse.ml.cbs.alpha.gr/ReferenceData/">
	<ref:getListReferenceDataItemPayload>
		<ref:RequestDataList>
			<ref:RequestData>
				<ref:Name>ErrorMessages</ref:Name>
				<ref:Version>1</ref:Version>
				<ref:LanguageId>1</ref:LanguageId>
				<ref:SystemsId>1</ref:SystemsId>
				<ref:Value/>
			</ref:RequestData>
		</ref:RequestDataList>
		<ref:LoggingInfo>
			<ref:RequestId>fe9a0075-6035-4399-83e5-acd18efb0999</ref:RequestId>
			<ref:SessionId>c2dbd0fb-914e-4a</ref:SessionId>
			<ref:BusinessCaseId>08ced443-98f2-437c-b8e4-8b92cda8d9dc</ref:BusinessCaseId>
			<ref:SequenceId>1</ref:SequenceId>
			<ref:UserId>StressTest</ref:UserId>
			<ref:CBSUnId/>
		</ref:LoggingInfo>
		<ref:EnvParams>
			<ref:WorkingDate>2020-04-21</ref:WorkingDate>
			<ref:PreviousWorkingDate>2020-04-16</ref:PreviousWorkingDate>
			<ref:NextWorkingDate>2020-04-22</ref:NextWorkingDate>
			<ref:ResourceID>673</ref:ResourceID>
			<ref:UnitCodeLevel1>014</ref:UnitCodeLevel1>
			<ref:UnitTypeCodeLevel1>1</ref:UnitTypeCodeLevel1>
			<ref:UnitCodeLevel2>0096</ref:UnitCodeLevel2>
			<ref:UnitTypeCodeLevel2>03</ref:UnitTypeCodeLevel2>
			<ref:ChannelTypeCode>03</ref:ChannelTypeCode>
			<ref:ResourceTypeCode>05</ref:ResourceTypeCode>
			<ref:BusinessFlowName>SNP00001</ref:BusinessFlowName>
		</ref:EnvParams>
	</ref:getListReferenceDataItemPayload>
</ref:getListReferenceDataItem>
</soapenv:Body>
</soapenv:Envelope>
```

### PR DESCRIPTION
**Pull request by ppalaga**
fix #1066

### CODE REVIEW

**Comment by ppalaga** [comment]
@franz1981 @geoand I tried to implement your suggestions here: I have taken the latest `ResteasyReactiveOutputStream` from Quarkus and adapted it to work here as `VertxServletOutputStream`. I did very similar edits like @dufoli who ported it originally. 

Porting the part with `LazyResponse` was not easy so I have omitted it for now. Is this perhaps what you meant with "jackson approach mentioned earlier"?

I did some benchmarks and the performance on my machine is great:

- Before 7954 ms
- After 838 ms

**Comment by ppalaga** [comment]
Added comments explaining from where the two new classes originate.

**Review by franz1981 — APPROVED** [review]
LGTM, my only suggestion is related the tests; to avoid being captured by another regression, in the future, adding a test which ensure we are same or better than the expected number of packets, for a large write, would be great

**Comment by ppalaga** [comment]
9714f01: added the test ensuring that there is an expected number of chunks.

**Comment by ppalaga** [comment]
The way how I implemented the counting of chunks in ChunkedTest through overriding HTTP Client classes is all but elegant. Anybody knows of a nicer approach?

**Comment by ppalaga** [comment]
6da774a: made the CodeQL happy.

**Comment by franz1981** [comment]
These tests are never easy to be implemented...
So, you can do in different ways, actually:
- how you've done
- using an existing proxy which can count the http chunks coming from the server 
- mocking some class on the server and verify how http data is sent through it
- using Netty's Embeddable Channel and intercept how vertx send buffers to it 

As you can see non are really elegant, just some could make uses of existing bits to shorten the amount of code and appear better, because the ugliness is well confined elsewhere :P

**Comment by ppalaga** [comment]
Thanks for the suggestions, @franz1981! I think it would be better to avoid changing anything on the server so that we do not influence other tests (which are also run in native mode) in this module. I am not finding any usable proxy implementation.

Thus, I am going to merge like this.

**Comment by ppalaga** [comment]
Open Questions: 

1. You mentioned somewhere that it would be good to make the `org.jboss.resteasy.reactive.server.vertx.AppendBuffer` public, right? However, depending on `resteasy-reactive-vertx` here in Quarkus CXF would not be great. Can you perhaps see some module, from where we could re-use it both here and in `resteasy-reactive-vertx`? Somewhere in Vert.x maybe?
2. What's your opinion on creating a common parent for `io.quarkiverse.cxf.transport.VertxServletOutputStream` and `org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream`? IMO it would be great to have it so that Quarkus CXF does not miss any future fixes.

**Comment by franz1981** [comment]
Let me route these to @geoand which have a much better knowledge of quarkus's module deps, and I can help doing it

**Comment by geoand** [comment]
> Can you perhaps see some module, from where we could re-use it both here and in `resteasy-reactive-vertx` ?

Very unlikely

> What's your opinion on creating a common parent for io.quarkiverse.cxf.transport.VertxServletOutputStream and org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream ?

I really don't want such kind of coupling

**Comment by ppalaga** [comment]
Fair enough, thanks for the clear statement, @geoand

**Comment by geoand** [comment]
🙏

**Pull request merged**
