### PR TITLE
Fix dev mode reload #551

### PR DESCRIPTION
**Pull request by shumonsharif**

### CODE REVIEW

**Comment by shumonsharif** [comment]
@ppalaga Review would be welcome!

**Comment by ppalaga** [comment]
@shumonsharif I looked through it and I wonder whether we could fully get rid of VertxDestinationRegistryFactory given that 

* We do not want to keep its static state between the reloads
* There is nothing really Vert.x specific in it
* We could just create a new DestinationRegistryImpl in CxfHandler()

I tried to implement that in https://github.com/quarkiverse/quarkus-cxf/pull/561 I am curious whether some client tests are going to fail. 

Plus I have added a dev mode test that we can keep regardless which solution will turn out to be better.

**Comment by ppalaga** [comment]
https://github.com/quarkiverse/quarkus-cxf/pull/561 all tests passed, hence I'd vote for that fix because it is simpler.

**Comment by ppalaga** [comment]
> how Camel is leveraging Quarkus CXF - I hope we don't break that integration? See [#480 (comment)](https://github.com/quarkiverse/quarkus-cxf/pull/480#issue-1326310689)

Haha, maybe I just shoot into my own foot? Thanks for the pointer! Let me check.

**Pull request closed without merging**
